### ISSUE TITLE
Usage info

### ISSUE THREAD

**Issue by dsmith73** [jessestuart/covid_exporter#3]
You have no information on the usage of this.  

So, I assume...

a valid prom scrape_config is:  
```yml
  - job_name: 'covid_exporter'
    scrape_interval: 5m
    static_configs:
      - targets: ['covid_exporter:XXXX']
```

and a valid docker-compose source is:  
```yml
  covid_exporter:
    image: jessestuart/covid_exporter:latest
    ports:
      - XXXX:XXXX
    restart: always
    networks:
      - private
```

Is this all-in-one, or am I plugging it into my current Prometheus & Grafana setup?
